repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.404
    hooks:
      - id: pyright
        args: [--project, debt-collectibility/pyrightconfig.json]
  - repo: local
    hooks:
      - id: mypy
        name: mypy (src only, changed files)
        entry: uv run mypy
        language: system
        pass_filenames: true
        types_or: [python, pyi]
        files: ^debt-collectibility/src/.*\.py$
        args: [--show-error-codes, --pretty]
