name: Secrets scan

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: secrets-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pre-commit envs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install tooling (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==4.3.0

      - name: Ensure baseline exists
        run: |
          if [ ! -f ".secrets.baseline" ]; then
            echo "::error title=Missing baseline:: .secrets.baseline not found in repo root."
            exit 1
          fi

      - name: Run detect-secrets via pre-commit (all files)
        run: |
          pre-commit run detect-secrets --all-files --show-diff-on-failure
